server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospitaldb
    username: user1
    password: user1@sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

ehrbridge:
  app:
    jwtSecret: 655468576D5A7133743677397A24432646294A404E635266556A586E32723575
  gateway:
    apiKey: ajhkfjhsjkdhfjkshfjhskjhfsjkshjfkjsh
    host: http://localhost:8080
    consent-request:
      endpoint: /api/v1/consent/generate
    data-request:
      endpoint: /api/v1/data/request
    hospital-fetch-all:
      endpoint: /api/v1/hospitals/fetch-all
    hospital-fetch-id:
      endpoint: /api/v1/hospitals/fetch