server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospitaldbhip
    username: user1
    password: user1@sql
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

hospital:
  id: af913885-d38b-46a7-a586-f2224ea80c2a
ehrbridge:
  app:
    jwtSecret: 655468576D5A7133743677397A24432646294A404E635266556A586E32723575
  gateway:
    apiKey: ESgIEQY888Q2hdQ0T53FQircyv7wQetY
    host: http://localhost:8080
    consent-request:
      endpoint: /api/v1/consent/generate
    data-request:
      endpoint: /api/v1/data/request
    hospital-fetch-all:
      endpoint: /api/v1/hospitals/fetch-all
    hospital-fetch-id:
      endpoint: /api/v1/hospitals/fetch